version: '1'

services:
  flagify-app:
    build: .
    ports:
      - "8123:8123"
    env_file: .env
    depends_on:
      flagify-db:
        condition: service_healthy
  flagify-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '5438:5432'
    volumes:
      - ./db/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql