version: '1'

services:
  flagify-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=flagify
      - POSTGRES_PASSWORD=flagify
      - POSTGRES_DB=flagify
    ports:
      - '5438:5432'
    volumes:
      - ./db/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql