version: '1'

services:
  flagify-app:
    build: .
    ports:
      - "8123:8123"
    env_file: .env
    depends_on:
      - flagify-db
  flagify-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5438:5432'
    volumes:
      - ./db/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql